name: Check Links & Report Issues

on:
  schedule:
    - cron: '0 0 * * 0' # Every Sunday at midnight
  workflow_dispatch:

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Link Checker
        uses: lycheeverse/lychee-action@v2
        id: lychee
        with:
          args: >-
            --verbose
            --no-progress
            --max-redirects 10
            --max-retries 2
            --retry-wait-time 2
            --accept 403,405
            --exclude "^https?://(www\\.)?reuters\\.com/"
            --exclude "^https?://(www\\.)?washingtonpost\\.com/"
            "**/*.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Creates a structured Issue if dead links are found
      - name: Create Issue From Failures
        if: ${{ always() && steps.lychee.outcome == 'failure' && hashFiles('lychee/out.md') != '' }}
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: "Maintenance Alert: Dead or Broken Links Found"
          content-filepath: ./lychee/out.md
          labels: |
            bug
            automated-alert
