name: Auto-Format Markdown

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# EXPLICITLY PERMIT GITHUB TO SAVE AND PUSH THE FORMATTED FILES
permissions:
  contents: write

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Prettier
        uses: creyder/prettier_action@v4.3
        with:
          prettier_options: --write **/*.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
